#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create users and database
    CREATE 
        USER $HEIMDALLR_POSTGRES_APP_USER 
        WITH PASSWORD '$HEIMDALLR_POSTGRES_APP_PASSWORD';
    CREATE 
        USER $HEIMDALLR_POSTGRES_MIGRATOR_USER 
        WITH PASSWORD '$HEIMDALLR_POSTGRES_MIGRATOR_PASSWORD';

    -- Grant all privileges, and set default privileges to grant on all future tables
    GRANT 
        ALL PRIVILEGES 
        ON ALL TABLES IN SCHEMA $HEIMDALLR_POSTGRES_SCHEMA
        TO $HEIMDALLR_POSTGRES_MIGRATOR_USER;
    GRANT 
        ALL PRIVILEGES 
        ON SCHEMA $HEIMDALLR_POSTGRES_SCHEMA
        TO $HEIMDALLR_POSTGRES_MIGRATOR_USER;

    ALTER DEFAULT PRIVILEGES 
        FOR USER $HEIMDALLR_POSTGRES_MIGRATOR_USER 
        IN SCHEMA $HEIMDALLR_POSTGRES_SCHEMA 
        GRANT ALL 
            ON TABLES 
            TO $HEIMDALLR_POSTGRES_MIGRATOR_USER;

    ALTER DEFAULT PRIVILEGES 
        FOR USER $HEIMDALLR_POSTGRES_MIGRATOR_USER 
        IN SCHEMA $HEIMDALLR_POSTGRES_SCHEMA 
        GRANT 
            SELECT, UPDATE, INSERT, DELETE 
            ON TABLES 
            TO $HEIMDALLR_POSTGRES_APP_USER;
EOSQL