//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ChangeRequestsStream struct {
	ID                uuid.UUID `sql:"primary_key"`
	AggregateID       string
	OccurredAt        *time.Time
	Payload           string
	Type              *string
	SourceID          *uuid.UUID
	SourceIntegration string
}
