//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserAccessTokens struct {
	ID        string `sql:"primary_key"`
	Secret    string
	ExpiresAt *time.Time
	UserID    uuid.UUID
}
