logging:
  level: debug
  format: json

api:
  server:
    debug_errors_enabled: false
    port: 8080
    access_log:
      format: json
      enabled: true


auth:
  # Temporary to get some basic auth in
  master_token: "****"
  bcrypt:
    # High costs can result in pretty slow API requests
    # It will be used on every API request, so needs to be a balance between 
    # security and performance.
    # 12 is probably a minimum
    cost: 12

db:
  event_store:
    driver: postgres

    postgres:
      host: "postgres"
      password: "iampostgres"
      user: "panoptes-app"
      port: 5432
      database: "panoptes"
      schema: "public"

  projection:
    driver: opensearch

# Exemplary only, still toying with this, but helps me map it out
metrics:
  - name: "Coding Time"
    slug: "coding-time"
    description: |
      The time the developer spent coding the changes.
    stream: task
    countWhile:
      - allOf:
        - anyOf:
          - change_request:
              is_draft: true
          - change_request:
              does_not_exist: true
        - task:
            status: ["in progress"]

  - name: "Review Time"
    slug: "review-time"
    stream: task
    description: |
      The time that it took to review the changes.
    startOn:
      - vcs:
          comment_added:
    stopOnLast:
      - change_request:
          approved:
      - change_request:
          merged:
      - change_request:
          closed:
      - task:
          status_changed:
            from: ["awaiting review"]
